import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, Cloud, Code2, Download, Gamepad2, KeyRound, Layers3, Package, Palette, Rocket, Search, ShieldCheck, Terminal, Wrench } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useMemo, useState, type ReactNode } from 'react'

type SectionInfo = {
  slug: string
  title: string
  description: string
  icon: typeof BookOpen
  status: 'Current' | 'Reference'
}

const sections: SectionInfo[] = [
  { slug: 'getting-started', title: 'Getting Started', description: 'First launch, importing existing libraries, adding games, identifying games, and launching them.', icon: Rocket, status: 'Current' },
  { slug: 'install', title: 'Install, Updates & Offline', description: 'Linux and macOS installs, verified downloads, in-app updates, and what works without a network.', icon: Download, status: 'Current' },
  { slug: 'library', title: 'Library Management', description: 'Pikos, Tofus, sources, categories, metadata, local storage, and machine-specific paths.', icon: Gamepad2, status: 'Current' },
  { slug: 'launching', title: 'Launching Games', description: 'Native executables, desktop entries, Flatpaks, scripts, Wine/Proton, and source-launcher handoff.', icon: Terminal, status: 'Current' },
  { slug: 'mods', title: 'Mods & Content', description: 'Discover and install mods from Modrinth, CurseForge, and Nexus Mods into a Tofu, with updates and nxm:// links.', icon: Package, status: 'Current' },
  { slug: 'integrations', title: 'Integrations & Metadata', description: 'IGDB, SteamGridDB, and Steam Store metadata, service keys, downloads, and integration boundaries.', icon: Layers3, status: 'Current' },
  { slug: 'experience', title: 'Big Picture, Themes & Stats', description: 'Controller-first Big Picture mode, Steam Deck, themes, accessibility, playtime stats, and achievements.', icon: Palette, status: 'Current' },
  { slug: 'account', title: 'Account & Security', description: 'Sign-in methods, account switching, authenticator app, passkeys, linked accounts, and service keys.', icon: ShieldCheck, status: 'Current' },
  { slug: 'cloud-sync', title: 'Mochi Cloud', description: 'Optional metadata synchronisation, Cloud access, Cloud sync, ownership, and local-first boundaries.', icon: Cloud, status: 'Current' },
  { slug: 'development', title: 'Development', description: 'React, Tauri 2, Rust, platform/source adapters, themes, native commands, and development workflow.', icon: Code2, status: 'Reference' },
  { slug: 'reference', title: 'Reference', description: 'Glossary, platform matrix, launch target matrix, storage locations, deep links, and troubleshooting.', icon: BookOpen, status: 'Reference' },
]

const headings: Record<string, Array<[string, string]>> = {
  install: [['platforms','Supported platforms'],['linux','Linux'],['macos','macOS'],['verify','Verified downloads'],['updates','Updates'],['offline','Offline mode']],
  mods: [['overview','Overview'],['sources','Sources and games'],['discover','Discover and install'],['per-tofu','Per-Tofu mods'],['updates','Update checks'],['nxm','nxm:// links'],['curseforge','CurseForge notes'],['deps','Dependencies and conflicts'],['snapshots','Snapshots and Update all'],['mochipack','Modpacks (.mochipack)'],['minecraft','Minecraft instances']],
  experience: [['bigpicture','Big Picture'],['controller','Controller support'],['steamdeck','Steam Deck'],['themes','Themes'],['accessibility','Accessibility'],['sounds','Interface sounds'],['stats','Playtime and stats'],['achievements','Achievements']],
  'getting-started': [['overview','Overview'],['first-launch','First launch'],['importing','Import existing games'],['add-game','Add a game'],['identify','Game metadata'],['tofu','Tofu environments'],['play','Launch and play'],['troubleshooting','Troubleshooting']],
  library: [['model','Piko + Tofu'],['piko','Pikos'],['tofu','Tofus'],['sources','Game sources'],['categories','Collections and tags'],['backlog','Backlog and wishlist'],['duplicates','Duplicate games'],['metadata','Metadata'],['local','Local storage'],['storage','Storage manager'],['saves','Save backups'],['library-backup','Library backup'],['settings-backup','Settings backup'],['paths','Machine-specific paths']],
  launching: [['targets','Launch targets'],['executable','Executables'],['desktop','.desktop files'],['flatpak','Flatpak'],['scripts','Scripts'],['wine','Wine, Proton, CrossOver'],['options','Launch options'],['shortcuts','Shortcuts and Add to Steam'],['cli','Command line'],['sources','Source handoff'],['tracked','Playtime tracking'],['platforms','Platform behaviour'],['errors','Errors']],
  integrations: [['overview','Integration model'],['igdb','Metadata providers'],['matching','Matching and confirmation'],['modrinth','Modrinth'],['downloads','Downloads'],['credentials','Service keys'],['nexus-api-key','Adding your Nexus Mods API key'],['limits','Integration boundaries'],['experimental','Experimental features']],
  account: [['methods','Authentication'],['switching','Account switching'],['sessions','Sessions'],['totp','Authenticator app'],['passkeys','Passkeys'],['identities','Linked accounts'],['profile','Profiles and avatars'],['credentials','Credential security']],
  'cloud-sync': [['principles','Principles'],['access','Cloud access and Cloud sync'],['data','Synchronised data'],['pull','Pull behaviour'],['push','Push behaviour'],['ownership','Ownership and RLS'],['local','Local boundary'],['failure','Failure handling']],
  development: [['stack','Technology stack'],['architecture','Architecture'],['frontend','Frontend'],['native','Tauri/Rust'],['platforms','Platform adapters'],['sources','Source adapters'],['themes','Theme system'],['local','Local development'],['build','Builds']],
  reference: [['glossary','Glossary'],['platforms','Platform matrix'],['targets','Launch matrix'],['storage','Storage'],['deeplinks','Deep links'],['states','Feature states'],['troubleshooting','Troubleshooting']],
}

function Section({ id, title, children }: { id: string; title: string; children: ReactNode }) {
  return <section id={id} className="scroll-mt-28 border-b border-white/10 pb-9 pt-2">
    <h2 className="text-2xl font-bold tracking-tight text-white">{title}</h2>
    <div className="mt-4 space-y-4 text-[15px] leading-7 text-slate-300">{children}</div>
  </section>
}

function Callout({ icon: Icon = Wrench, title, children }: { icon?: typeof Wrench; title: string; children: ReactNode }) {
  return <div className="rounded-2xl border border-violet-400/15 bg-violet-500/[0.05] p-5"><div className="flex items-start gap-3"><Icon className="mt-1 h-5 w-5 shrink-0 text-violet-300" /><div><p className="font-semibold text-white">{title}</p><div className="mt-1 text-sm leading-6 text-slate-400">{children}</div></div></div></div>
}

function Diagram({ title, children }: { title: string; children: ReactNode }) {
  return <div className="my-7 overflow-x-auto rounded-2xl border border-white/10 bg-black/20 p-5"><p className="mb-4 text-xs font-semibold uppercase tracking-[0.16em] text-violet-300">{title}</p>{children}</div>
}

function Box({ title, children, muted = false }: { title: string; children?: ReactNode; muted?: boolean }) {
  return <div className={`min-w-[155px] rounded-xl border px-4 py-3 text-center ${muted ? 'border-white/10 bg-white/[0.03]' : 'border-violet-400/25 bg-violet-500/[0.07]'}`}><p className="text-sm font-semibold text-white">{title}</p>{children && <p className="mt-1 text-xs leading-5 text-slate-400">{children}</p>}</div>
}

export function DocumentationPage() {
  const [query, setQuery] = useState('')
  const filtered = useMemo(() => {
    const value = query.trim().toLowerCase()
    return value ? sections.filter(s => `${s.title} ${s.description}`.toLowerCase().includes(value)) : sections
  }, [query])

  return <div className="space-y-10 pb-10">
    <header className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-br from-violet-500/10 via-slate-950/70 to-cyan-500/10 p-7 sm:p-10">
      <div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-violet-500/10 blur-3xl" />
      <div className="relative">
        <div className="inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-500/10 px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.18em] text-violet-200"><BookOpen className="h-3.5 w-3.5" /> Documentation</div>
        <h1 className="mt-5 max-w-4xl text-4xl font-black tracking-tight text-white sm:text-5xl">How Mochi actually works.</h1>
        <p className="mt-5 max-w-4xl text-lg leading-8 text-slate-300">This documentation follows the current Mochi Launcher implementation: a Tauri desktop launcher for Linux and macOS (Linux is the primary, best-tested platform; Windows is not supported) with local game management, source importing, metadata, mods from Modrinth, CurseForge, and Nexus Mods, a controller-first Big Picture mode, themes, achievements, account security, and optional cloud metadata. Mochi is in early development, so formats and screens may still change.</p>
        <div className="mt-7 flex max-w-2xl items-center gap-3 rounded-2xl border border-white/10 bg-black/20 px-4 py-3"><Search className="h-5 w-5 text-slate-500" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search documentation sections..." className="w-full bg-transparent text-sm text-white outline-none placeholder:text-slate-600" /></div>
      </div>
    </header>
    <div className="grid gap-4 md:grid-cols-2">
      {filtered.map(({ slug, title, description, icon: Icon, status }) => <Link key={slug} to={`/documentation/${slug}`} className="glass-card group p-6 transition hover:-translate-y-0.5 hover:border-violet-400/25"><div className="flex items-start justify-between gap-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/10 bg-white/[0.04]"><Icon className="h-5 w-5 text-violet-300" /></div><span className="rounded-full border border-white/10 bg-white/[0.03] px-2.5 py-1 text-[11px] font-semibold text-slate-400">{status}</span></div><h2 className="mt-5 text-xl font-bold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{description}</p><div className="mt-5 flex items-center gap-2 text-sm font-semibold text-violet-300">Read documentation <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></div></Link>)}
    </div>
    {!filtered.length && <div className="glass-card p-8 text-center text-sm text-slate-400">No documentation sections match <strong className="text-slate-200">{query}</strong>.</div>}
  </div>
}

export function DocumentationArticlePage() {
  const { section } = useParams()
  const index = sections.findIndex(item => item.slug === section)
  const current = sections[index]
  if (!current) return <div className="glass-card p-10"><h1 className="text-2xl font-bold text-white">Documentation not found</h1><Link className="mt-4 inline-flex text-violet-300" to="/documentation">Back to documentation</Link></div>
  const previous = sections[index - 1]
  const next = sections[index + 1]
  return <div className="pb-10">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><Link to="/documentation" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-400 transition hover:text-white"><ArrowLeft className="h-4 w-4" /> Back to docs</Link><span className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-600">{current.status}</span></div>
    <div className="grid gap-8 lg:grid-cols-[220px_1fr]">
      <aside className="hidden lg:block"><div className="sticky top-24 space-y-2"><p className="px-3 pb-2 text-xs font-semibold uppercase tracking-[0.18em] text-slate-600">On this page</p>{headings[current.slug].map(([id, title]) => <a key={id} href={`#${id}`} className="block rounded-lg px-3 py-2 text-sm text-slate-500 transition hover:bg-white/[0.04] hover:text-slate-200">{title}</a>)}</div></aside>
      <article className="min-w-0"><header className="mb-9"><div className="inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-500/10 px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.16em] text-violet-200"><current.icon className="h-3.5 w-3.5" /> {current.title}</div><h1 className="mt-5 text-4xl font-black tracking-tight text-white sm:text-5xl">{current.title}</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-400">{current.description}</p></header>{renderArticle(current.slug)}<nav className="mt-10 grid gap-3 sm:grid-cols-2">{previous ? <Link to={`/documentation/${previous.slug}`} className="glass-card p-4"><span className="text-xs text-slate-500">Previous</span><span className="mt-1 flex items-center gap-2 font-semibold text-white"><ArrowLeft className="h-4 w-4" />{previous.title}</span></Link> : <span />}{next ? <Link to={`/documentation/${next.slug}`} className="glass-card p-4 text-right"><span className="text-xs text-slate-500">Next</span><span className="mt-1 flex items-center justify-end gap-2 font-semibold text-white">{next.title}<ArrowRight className="h-4 w-4" /></span></Link> : <span />}</nav></article>
    </div>
  </div>
}

function renderArticle(slug: string): ReactNode {
  const articles: Record<string, () => ReactNode> = {
    'getting-started': GettingStarted, install: Install, library: Library, launching: Launching, mods: Mods,
    integrations: Integrations, experience: Experience, account: Account, 'cloud-sync': CloudSync,
    development: Development, reference: Reference,
  }
  return articles[slug]?.() ?? null
}

function GettingStarted() { return <div className="space-y-9">
  <Section id="overview" title="1. What you are installing"><p>Mochi is a desktop game launcher. It runs on Linux and macOS and does not replace Steam, Heroic, Lutris, Bottles, itch.io, Flatpak, or the games themselves. Instead, it gives those games a single library and launches them using the appropriate target or source launcher.</p><Callout icon={CheckCircle2} title="Local first">A Mochi account and Mochi Cloud are optional. Your local library and game installations remain on the device.</Callout></Section>
  <Section id="first-launch" title="2. First-launch setup"><p>The guided setup is split into Welcome, Account, metadata, and Game Imports. Account and metadata configuration are optional. The import stage detects supported sources and lets you select what to scan.</p><p>Setup remembers completion locally. It can be reset from Mochi's app-data controls. Search the library any time with Ctrl+K (Cmd+K on macOS).</p></Section>
  <Section id="importing" title="3. Import existing games"><p>Mochi can detect and scan existing game sources instead of requiring every game to be added manually.</p><ul className="list-disc space-y-2 pl-6"><li><strong>Steam</strong> — installed Steam games from your libraries and non-Steam shortcuts.</li><li><strong>Heroic Games Launcher</strong> — installed Epic, GOG, and Amazon games represented in Heroic's local configuration.</li><li><strong>Lutris</strong> and <strong>Bottles</strong> (Linux) — existing Lutris games and Bottles programs.</li><li><strong>itch.io</strong> — games represented by itch receipts.</li><li><strong>Flatpak</strong> (Linux) — installed Flatpak applications categorised as games.</li><li><strong>Epic Games Launcher</strong> and <strong>Whisky</strong> pins (macOS), plus desktop applications and <code>.app</code> bundles.</li></ul><p>Imports are non-destructive: Mochi records a launch target and installation information rather than moving, copying, or uninstalling anything. Mochi detects installed runtimes such as Wine, Proton, and CrossOver but does not install them.</p></Section>
  <Section id="add-game" title="4. Add a game manually"><p>For a custom game, choose the target with the native file picker or enter a supported target manually. Linux can also select an installed Flatpak by application ID. Windows <code>.exe</code> files can be added through Wine or Proton on Linux and CrossOver or Whisky on macOS.</p><p>If a metadata provider is configured, the add flow moves to a separate matching step rather than silently guessing the game's identity.</p></Section>
  <Section id="identify" title="5. Identify a game"><p>Mochi can use IGDB (with your Twitch client ID and secret saved as service keys), SteamGridDB (artwork), and the Steam Store (Steam games, no key). For IGDB it searches for up to six likely candidates. Each candidate can provide a name, summary, cover/artwork, genres, and release information. You can approve the proposed match or choose another result. You can also continue without metadata. Custom artwork you set is never overwritten, and fetched metadata is cached so it still shows offline.</p></Section>
  <Section id="tofu" title="6. Create and use a Tofu"><p>A Piko is the game identity; a Tofu is an environment or configuration for running that game. A Piko can contain multiple Tofus, such as separate versions, modded profiles, or runtimes. Each Tofu has its own content folder, launch settings, and mods (see Mods &amp; Content).</p></Section>
  <Section id="play" title="7. Launch and play"><p>Launching a Piko calls the native backend. Playtime is credited when the game exits, including games handed to another launcher, and a Stop button ends a running game. Closing the window can leave Mochi running in the tray.</p></Section>
  <Section id="troubleshooting" title="8. Troubleshooting"><p>If a launch fails, first verify the target still exists and that its owning launcher is installed and available. For imported games, the source application's own runtime, prefix, authentication, or configuration may still be required.</p><p>For support reports, include the OS, Mochi version, source or launch-target type, and the exact error message.</p></Section>
</div> }

function Library() { return <div className="space-y-9">
  <Section id="model" title="1. Piko + Tofu"><Diagram title="Core library model"><div className="flex flex-col items-center gap-3 sm:flex-row sm:justify-center"><Box title="Piko" >Game identity</Box><ArrowRight className="hidden h-5 w-5 text-slate-600 sm:block" /><div className="text-slate-600 sm:hidden">↓</div><Box title="Tofu" >Environment / profile</Box></div></Diagram><p><strong>Piko</strong> answers “what game is this?” while <strong>Tofu</strong> answers “how is this version or setup run?”</p></Section>
  <Section id="piko" title="2. Pikos"><p>A Piko contains the game's name, description, accent/artwork, categories, source information, launch target, and its Tofus. Source-aware imports can retain a source ID such as Steam, Heroic, Lutris, Bottles, itch.io, or Flatpak.</p></Section>
  <Section id="tofu" title="3. Tofus"><p>A Tofu is an install, version, modded profile, or runtime of a Piko. It contains a name, game version, runtime, mod count, status, and optional install path and content folder. The install path is especially important for local content management and is not assumed to be portable between computers.</p></Section>
  <Section id="sources" title="4. Game sources"><p>Source integrations discover existing installations without taking ownership of them. Steam shortcuts, for example, are launched through Steam so Steam keeps control of its launch context.</p></Section>
  <Section id="categories" title="5. Collections and tags"><p>Ctrl/Cmd+K opens a command palette that searches games and runs actions (go to a page, switch theme, add or import games, snapshot a Tofu, check mod updates); <code>&gt;</code> limits it to actions. The top-bar search matches names, descriptions, and categories. You can sort, mark favourites, add tags and collections, and use smart filters: All, Favourites, Installed, Recently played, Unplayed, Most played, Launchers, and Running now, and Backlog. Any combination of status, played, tags, genres and hours-to-beat can be saved as a named filter chip. A Continue playing row shows recent games. The grid is one Tab stop: arrow keys, Home/End, Page Up/Down and typing a name move between games, Enter opens, Shift+Enter plays, Ctrl/Cmd+D favourites and <code>/</code> focuses search; press <code>?</code> for the list. On Linux, Steam games show a ProtonDB tier badge, fetched on demand. Settings → Appearance has a game-themes switch that uses each game's cover colour as the accent on its page. Steam soundtracks and extras are tucked into a collapsed section, and games with placeholder art are listed after games with metadata.</p></Section>
  <Section id="backlog" title="6. Backlog and wishlist"><p>Give a game a backlog status (want, playing, finished, dropped) and a note from its page, card menu or editor; the Backlog filter lists want and playing. The Wishlist chip tracks games you do not own, and a What should I play? picker suggests something from your library, using IGDB time-to-beat hours when IGDB is connected. Mark backlog games Next up so the picker favours them. All of this is local; backlog data is not cloud-synced.</p></Section>
  <Section id="duplicates" title="7. Duplicate games"><p>When the same game was imported from several places (Steam, Heroic, Flatpak, a desktop entry), Mochi offers to merge the copies into one Piko with a Play via choice. Nothing is deleted, no game files are touched, and you can unmerge or dismiss a pair as not the same game.</p></Section>
  <Section id="metadata" title="8. Metadata"><p>Metadata is enrichment, not ownership. Artwork, summaries, genres, and release information can make a Piko easier to identify while the underlying installation remains local. Settings → Data has Find missing covers for games that only have a generated cover, and the Edit game window has a Notes tab for plain-text notes and web links, shown on the game page.</p></Section>
  <Section id="local" title="9. Local storage"><p>The local Piko library and launcher preferences are stored on the device. Native application state such as playtime, themes, artwork, and Wine prefixes is handled by the Tauri/Rust layer. See Reference for locations.</p></Section>
  <Section id="storage" title="10. Storage manager"><p>Settings → Storage measures where disk space goes (game installs, mods, and Mochi's own caches, themes, sound packs, snapshots, save backups, Wine prefixes) and clears only Mochi's caches, one by one or all at once with Clear all unused data. It never deletes game installs or mod folders; for those it only offers Open.</p></Section>
  <Section id="saves" title="11. Save backups"><p>On a game page, Saves makes zip backups of Minecraft worlds, Steam userdata, and any folder you add, restores them safely, and can back up automatically when a game closes. Added folders stay on this device.</p></Section>
  <Section id="library-backup" title="12. Library backup"><p>Settings → Data creates a single <code>.mochibackup</code> file with your games, collections, wishlist, saved filters, and per-game notes, with an optional automatic copy to a folder (daily, weekly, or monthly; the newest few are kept). It holds no credentials and no playtime history.</p></Section>
  <Section id="settings-backup" title="13. Settings backup"><p>Settings → Data exports your preferences, themes, collections, wishlist, and per-game options to a zip and imports them on another device after a preview. Provider keys, sessions, and credential-looking launch variables are never included.</p></Section>
  <Section id="paths" title="14. Machine-specific paths"><Callout title="Paths are not portable">A local executable or Tofu directory can be valid on one machine and invalid on another. Cloud metadata does not magically make a local installation available elsewhere.</Callout></Section>
</div> }

function Launching() { return <div className="space-y-9">
  <Section id="targets" title="1. Supported launch targets"><p>The frontend normalises launch targets before passing them to the native layer. Linux and macOS both support file targets and source-aware targets; Flatpak is Linux only.</p><div className="overflow-x-auto rounded-2xl border border-white/10"><table className="w-full text-left text-sm"><thead className="bg-white/[0.03] text-slate-400"><tr><th className="p-3">Target</th><th className="p-3">Linux behaviour</th><th className="p-3">macOS</th></tr></thead><tbody className="divide-y divide-white/10 text-slate-300"><tr><td className="p-3">Executable</td><td className="p-3">Direct process launch</td><td className="p-3">Direct process launch</td></tr><tr><td className="p-3">.desktop</td><td className="p-3">gio launch, xdg-open fallback</td><td className="p-3">Not applicable</td></tr><tr><td className="p-3">Flatpak</td><td className="p-3">flatpak run</td><td className="p-3">Not applicable</td></tr><tr><td className="p-3">.app bundle</td><td className="p-3">Not applicable</td><td className="p-3">Opened as an application</td></tr><tr><td className="p-3">.exe</td><td className="p-3">Wine or Proton (GameMode, MangoHud optional)</td><td className="p-3">CrossOver or Whisky</td></tr><tr><td className="p-3">.sh / .bash</td><td className="p-3">sh</td><td className="p-3">sh</td></tr><tr><td className="p-3">.py / .js</td><td className="p-3">python3 / node</td><td className="p-3">Not explicitly handled</td></tr></tbody></table></div></Section>
  <Section id="executable" title="2. Executables"><p>Ordinary file targets are passed to the operating system as processes. Mochi does not construct a shell command string for a normal executable target.</p></Section>
  <Section id="desktop" title="3. .desktop files"><p>Linux desktop entries are launched through <code>gio launch</code>, with <code>xdg-open</code> as a fallback. This lets the desktop environment resolve the application entry.</p></Section>
  <Section id="flatpak" title="4. Flatpak"><p>Linux can also import Epic games installed with Legendary or Rare and Amazon games installed with Nile, launched through those tools. Linux can discover installed Flatpaks and categorise them using their application metadata. Game Flatpaks are prioritised in the picker. Mochi stores a normalised <code>flatpak://application.id</code> target and invokes <code>flatpak run</code> at launch.</p></Section>
  <Section id="scripts" title="5. Scripts"><p>Linux supports <code>.sh</code> and <code>.bash</code> through <code>sh</code>, <code>.py</code> through <code>python3</code>, and <code>.js</code> through <code>node</code>. macOS explicitly handles shell scripts and otherwise launches the selected target directly.</p></Section>
  <Section id="wine" title="6. Wine, Proton, and CrossOver"><p>Windows executables run through a compatibility layer: Wine or Proton on Linux (with optional GameMode and MangoHud), and CrossOver or Whisky on macOS. Mochi detects these runtimes but does not install them. Wine prefixes live in Mochi's native data directory.</p></Section>
  <Section id="options" title="7. Launch options"><p>Under Edit game → Launch you can set environment variables, arguments, and a working directory per game. On Linux you can also pick the Windows runtime (system Wine or a detected Proton) and wrap the launch in GameMode, MangoHud, or gamescope, with a live command preview. Arguments are passed separately, never through a shell. You can keep alternative option sets as launch profiles (for example another Proton version) and switch from the game page or the command palette. For Windows games on Linux, the Launch options tab also has a Wine/Proton prefix manager: prefix location and size, Wine settings, registry, repair, a short list of winetricks components, and a reset that keeps the old copy for restore. On macOS only variables, arguments, and working directory apply.</p></Section>
  <Section id="shortcuts" title="8. Shortcuts and Add to Steam"><p>A game page's Shortcuts menu (any game) creates an application-menu or desktop shortcut on Linux, or a small app bundle on macOS, and can add the game to Steam. Each one opens a <code>mochi://launch</code> link, so it survives Mochi being moved or updated.</p></Section>
  <Section id="cli" title="9. Command line"><p><code>mochi launch &lt;game&gt;</code> starts a library game, <code>mochi open &lt;game&gt;</code> shows its page, and <code>mochi list [--json]</code> prints your library. The same links work as <code>mochi://launch/…</code> and <code>mochi://open/…</code>. Commands only act on games already in your library and go through the normal launch path.</p></Section>
  <Section id="sources" title="10. Source-launcher handoff"><p>Imported games may use source-specific targets so the original launcher remains responsible for its environment.</p><ul className="list-disc space-y-2 pl-6"><li>Steam: <code>steam://rungameid/…</code></li><li>Heroic: Heroic launch URI</li><li>Lutris: <code>lutris:rungameid/…</code></li><li>Bottles: <code>bottles:run/…</code></li><li>itch.io: itch game launch integration</li></ul></Section>
  <Section id="tracked" title="11. Playtime tracking"><p>Mochi starts a playtime session when launching a game and credits it on exit, also for games handed to another launcher. Playtime is stored by the native layer and feeds the Stats view (recent sessions and a year-in-review summary) and achievements. The tray menu also lists up to five most-played games.</p></Section>
  <Section id="platforms" title="12. Platform behaviour"><p>Linux is the primary, best-tested platform and has the broadest integrations. macOS (12.0 or later, Apple silicon and Intel) has its own native adapter with executable, shell-script, and application-bundle launching, and is less tested. Windows is not supported.</p></Section>
  <Section id="errors" title="13. Errors"><p>Common failures include missing executables, unavailable source launchers, invalid Flatpak IDs, missing runtimes such as Python/Node, or inaccessible paths. The native backend returns an error rather than silently claiming that the launch succeeded. Mochi offers Copy debug info (secrets and your user name removed). If a game closes within 15 seconds of starting, Mochi notifies you with likely causes, including a rollback hint after a recent mod update, and a game's Logs has Find suspect mods with a switch-off button for each mod the log names.</p></Section>
</div> }

function Integrations() { return <div className="space-y-9">
  <Section id="overview" title="1. Integration model"><p>Integrations enrich or manage existing local games; Mochi is not a replacement store. The launcher should remain useful if an external service is offline or unavailable.</p></Section>
  <Section id="igdb" title="2. Metadata providers"><p><strong>IGDB</strong> needs a Twitch client ID and secret, <strong>SteamGridDB</strong> needs an API key, and the <strong>Steam Store</strong> needs no key and covers Steam games. Keys are stored server-side and never returned to the app. Metadata and artwork are cached and work offline; your own custom artwork is never overwritten.</p><Callout icon={KeyRound} title="Keys are sensitive">Twitch client secrets and other keys must never be committed to source code or posted in public issues.</Callout></Section>
  <Section id="matching" title="3. Matching and confirmation"><p>When adding a game with IGDB configured, Mochi requests up to six likely candidates. The user explicitly approves the selected identity or chooses another candidate. This avoids trusting a game name as a unique identifier.</p></Section>
  <Section id="modrinth" title="4. Modrinth"><p>Modrinth is one of three mod sources (with CurseForge and Nexus Mods; see Mods &amp; Content). For Minecraft Java Tofus you can search <strong>mods, modpacks, resource packs, and shaders</strong>, filter by Minecraft version and loader, inspect installed content, and manage files inside a Tofu. Downloads are restricted by the native backend to each provider's allowed hosts.</p></Section>
  <Section id="downloads" title="5. Background downloads"><p>Mod downloads run through the native layer with a size cap and SHA-1 check where the provider supplies one, and expose progress, completion, and failure state. Downloads can continue while Mochi is hidden in the tray. Completed entries are retained for ten minutes before cleanup. The Downloads page can pause and resume all downloads and sets a shared speed limit and allowed hours.</p></Section>
  <Section id="credentials" title="6. Service keys">
  <p>A service key is a credential for an outside service, saved privately on your Account and never shown again after saving. IGDB and Nexus Mods keys are managed under Security → Service keys in your dashboard; the app only learns whether a key is configured. CurseForge needs no key from you because Mochi uses its own server-side key.</p>
  <Section id="nexus-api-key" title="Adding your Nexus Mods API key">
    <p>Mochi's Nexus Mods integration uses a <strong>Personal API Key</strong>. Do not use an API key belonging to another application, such as an application-specific key shown for a registered mod manager or integration. The Personal API Key is the user-level key intended for personal/testing API access.</p>
    <p><strong>1. Open the Nexus Mods API keys page.</strong> Sign in to your Nexus Mods account, then open <a href="https://www.nexusmods.com/settings/api-keys" target="_blank" rel="noreferrer">Nexus Mods → API Keys</a>. If Nexus Mods asks you to sign in again, complete that first.</p>
    <p><strong>2. Find the “Personal API Key” section.</strong> The API keys page contains multiple keys and application-specific entries. For Mochi, scroll to the <strong>Personal API Key</strong> section, which is the user-level key for your own Nexus Mods account. <strong>This is the key you should copy into Mochi.</strong></p>
    <Callout icon={KeyRound} title="Use this exact key">Choose <strong>Personal API Key</strong>. Do not copy a key labelled for Mod Organizer 2, Vortex, another registered application, or another third-party tool. Mochi's Nexus Mods service key expects the value of your Personal API Key.</Callout>
    <p><strong>3. Generate or reveal the Personal API Key.</strong> If you do not already have a Personal API Key, use the control provided in that section to generate one. If Nexus Mods displays an existing key, use the copy control and copy the entire key exactly as shown. Never add quotes, spaces, or other text around it.</p>
    <p>Mochi checks that the key contains at least 32 printable characters with no spaces or line breaks, then asks Nexus Mods to validate it before storing. This catches incomplete, malformed, and revoked keys before they can break game discovery.</p>
    <p><strong>4. Open your Mochi dashboard.</strong> Sign in to the website, go to <strong>Security → Service keys</strong>, and find the <strong>Nexus Mods</strong> entry. This is separate from the IGDB key.</p>
    <p><strong>5. Paste the key into the Nexus Mods field.</strong> Paste the complete Personal API Key. You do not need to enter your Nexus Mods username or password, and you should not paste an IGDB Client ID or Client Secret into this field.</p>
    <p><strong>6. Save the key.</strong> Select the save button. The key is stored privately and is not displayed again; Mochi only reports whether it is configured.</p>
    <p><strong>7. Verify it is configured.</strong> After saving, the Nexus Mods entry should show as configured. If it does not, or an error appears, check that you copied the <strong>Personal API Key</strong> in full and try again.</p>
    <Callout title="Keep your key private">Treat the Personal API Key like a password. Do not paste it into GitHub issues, Discord, screenshots, bug reports, source code, or chat messages. If you believe the key has been exposed, revoke/regenerate it from the Nexus Mods API keys page and then replace the service key.</Callout>
    <p><strong>Nexus Mods API policy:</strong> Nexus Mods states that Personal API Keys are intended for experimentation, testing builds, and personal-use applications. Public-facing applications intended for wider use should follow Nexus Mods' application registration process instead of relying on users' Personal API Keys. See the <a href="https://help.nexusmods.com/article/114-api-acceptable-use-policy" target="_blank" rel="noreferrer">Nexus Mods API Acceptable Use Policy</a> for the current requirements.</p>
  </Section>
</Section>
  <Section id="limits" title="7. Integration boundaries"><p>External APIs can fail, rate-limit, change their responses, or become unavailable. Mochi's core library and local launching should not depend on an integration being healthy.</p></Section>
  <Section id="experimental" title="8. News, deals, sharing and experimental features"><p>Several optional features are off by default. <strong>Game news</strong> adds Steam posts and mod updates to the notification bell, the <strong>Deals tab</strong> (Settings → Deals &amp; news) shows free games, sales, and wishlist price watches, a <strong>stats share card</strong> makes a local PNG, and <strong>game search</strong> finds any game from the command palette when an IGDB or SteamGridDB key is saved. Their requests go through the native layer or your saved keys. <strong>Plugins</strong> are the one feature still labelled experimental under Settings → Experimental (off by default): small folders that add command palette commands in a restricted sandbox without network access, so only install plugins you trust.</p></Section>
</div> }

function Account() { return <div className="space-y-9">
  <Section id="methods" title="1. Authentication"><p>The desktop launcher supports email/password, email sign-in codes, Google, GitHub, and passkeys. An account is optional. Email verification can return to the desktop application through a <code>mochi://</code> deep link.</p></Section>
  <Section id="switching" title="2. Account switching"><p>Mochi can remember up to five signed-in accounts locally. Switching restores the selected account session; invalid saved sessions are removed and require signing in again.</p><Callout title="Local session storage">Saved account session material is local application state. It should be treated as sensitive and must not be copied into bug reports or shared.</Callout></Section>
  <Section id="sessions" title="3. Sessions"><p>The authentication client persists sessions and listens for authentication changes. Signing in to an account does not automatically enable cloud synchronisation.</p></Section>
  <Section id="totp" title="4. Authenticator app"><p>The authenticator app is Mochi's time-based one-time-code second factor. Enrollment provides a QR/manual secret and requires a six-digit verification code before the factor becomes active.</p></Section>
  <Section id="passkeys" title="5. Passkeys"><p>Passkeys use WebAuthn and provide a separate passwordless/security-key style authentication method. They are managed independently from the authenticator app.</p></Section>
  <Section id="identities" title="6. Linked accounts"><p>You can link or unlink Google and GitHub accounts from your Account, and use them as sign-in methods without creating separate Mochi accounts.</p></Section>
  <Section id="profile" title="7. Profiles and avatars"><p>Profile information includes user-facing display information and an optional avatar URL. The launcher can fall back to a Gravatar-derived avatar or local initials when a custom/provider avatar is unavailable.</p></Section>
  <Section id="credentials" title="8. Credential security"><p>Service keys such as IGDB/Twitch and Nexus Mods are deliberately separate from ordinary library metadata. Saved keys are never returned to the launcher or website. The launcher ships only a public URL and publishable key.</p></Section>
</div> }

function CloudSync() { return <div className="space-y-9">
  <Section id="principles" title="1. Local first, cloud optional"><p>Mochi Cloud is an optional companion to the desktop library. The cloud system is for supported metadata, not game-file backup.</p></Section>
  <Section id="access" title="2. Cloud access and Cloud sync"><p><strong>Cloud access</strong> is permission, granted by an administrator, for an Account to use Mochi Cloud. <strong>Cloud sync</strong> is your own switch for syncing library metadata, and is only possible with Cloud access. Game files and local paths are never uploaded.</p></Section>
  <Section id="data" title="3. Synchronised data"><p>The current library model synchronises supported profile/Piko/Tofu metadata: names, descriptions, artwork/accents, categories, source information, launch metadata, Tofu names, versions, runtimes, counts, and statuses as represented by the cloud schema.</p><p>Machine-specific files and complete game installations are outside this boundary.</p><Callout title="Achievements sync">Mochi achievements can optionally be saved to Mochi Cloud with a per-device toggle in Settings → Achievements, and cleared there too. Steam achievement totals are never uploaded.</Callout></Section>
  <Section id="pull" title="4. Pull behaviour"><p>When a signed-in launcher starts cloud synchronisation, it pulls the account's Pikos and their Tofus. If cloud data exists, it becomes the current library state.</p></Section>
  <Section id="push" title="5. Push behaviour"><p>If the cloud library is empty during initial synchronisation, the local library can be used as the initial cloud state. Later local library changes are pushed after synchronisation has been initialised.</p></Section>
  <Section id="ownership" title="6. Ownership and row-level security"><p>Cloud records are account-scoped. Database row-level security and server-side functions are used to restrict access to the owning user and authorised administrative operations.</p></Section>
  <Section id="local" title="7. The local boundary"><Diagram title="Data boundary"><div className="flex flex-col items-center gap-3 sm:flex-row sm:justify-center"><Box title="Local machine" >Installations, paths, native files</Box><ArrowRight className="hidden h-5 w-5 text-slate-600 sm:block" /><Box title="Mochi Cloud" >Supported metadata</Box></div></Diagram><p>A synced Piko can arrive on another device, but the device still needs a valid local installation and launch target before that game can actually run.</p></Section>
  <Section id="failure" title="8. Failure handling"><p>Cloud errors set the launcher into an error state rather than pretending the library is synchronised. The local library remains the primary fallback.</p></Section>
</div> }

function Development() { return <div className="space-y-9">
  <Section id="stack" title="1. Technology stack"><div className="grid gap-3 sm:grid-cols-2"><Box title="React + TypeScript">Desktop UI</Box><Box title="Tauri 2">Desktop boundary</Box><Box title="Rust">Native/platform layer</Box><Box title="Vite">Frontend build</Box><Box title="Supabase">Auth + cloud metadata</Box><Box title="Mod providers">Modrinth, CurseForge, Nexus Mods</Box></div></Section>
  <Section id="architecture" title="2. Application architecture"><Diagram title="Main boundary"><div className="flex flex-col items-center gap-3 sm:flex-row sm:justify-center"><Box title="React UI" >Library, settings, account</Box><ArrowRight className="hidden h-5 w-5 text-slate-600 sm:block" /><Box title="src/lib" >Small typed wrappers</Box><ArrowRight className="hidden h-5 w-5 text-slate-600 sm:block" /><Box title="Tauri commands" >Native operations</Box><ArrowRight className="hidden h-5 w-5 text-slate-600 sm:block" /><Box title="Rust adapters" >OS/source integration</Box></div></Diagram></Section>
  <Section id="frontend" title="3. Frontend"><p><code>src/App.tsx</code> owns the main launcher experience. Focused libraries under <code>src/lib/</code> wrap cloud, authentication, metadata, mod providers, platform, source, service-key, and theme behaviour.</p><p>Reusable setup/import/content components live under <code>src/components/</code>.</p></Section>
  <Section id="native" title="4. Tauri and Rust"><p><code>src-tauri/src/main.rs</code> registers native commands for launching, source discovery, playtime, themes, notifications, and mod file management. Rust owns operations that require local filesystem/process access.</p></Section>
  <Section id="platforms" title="5. Platform adapters"><p><code>src-tauri/src/platform/</code> isolates Linux, macOS, and unsupported-platform behaviour. Linux currently exposes Flatpak support and source-aware launching; macOS exposes application-bundle and shell-script handling.</p></Section>
  <Section id="sources" title="6. Source adapters"><p><code>src-tauri/src/sources/</code> separates game discovery from the operating-system launch layer. Sources include Steam (and shortcuts), Heroic, itch.io, and desktop apps on both platforms, plus Flatpak, Lutris, and Bottles on Linux and Epic Launcher and Whisky on macOS.</p></Section>
  <Section id="themes" title="7. Theme system"><p>Mochi ships 11 built-in themes (see Big Picture, Themes &amp; Stats) and a user theme system. Users can import a single <code>theme.json</code> file or a complete theme folder containing CSS and assets. Theme data lives in the Mochi configuration area and can be moved to another directory.</p></Section>
  <Section id="local" title="8. Local development"><p>Install Node.js, npm, Rust/Cargo, Tauri's native dependencies, and the platform tools needed for the features you are testing. Run <code>npm install</code>, then <code>npm run tauri dev</code> for the desktop application or <code>npm run dev</code> for frontend-only work.</p></Section>
  <Section id="build" title="9. Builds"><p><code>npm run build</code> creates the frontend production build. <code>npm run tauri build</code> creates desktop packages for the target platform. Pushing a tag such as <code>vX.Y.Z</code> triggers the release workflow, which builds an AppImage, deb, rpm, and a universal macOS DMG. Mochi is licensed GPL-3.0-or-later.</p></Section>
</div> }

function Reference() { return <div className="space-y-9">
  <Section id="glossary" title="1. Glossary"><dl className="space-y-4"><div><dt className="font-semibold text-white">Piko</dt><dd className="text-slate-400">The top-level identity of a game in Mochi.</dd></div><div><dt className="font-semibold text-white">Tofu</dt><dd className="text-slate-400">One way of running a Piko: an environment, profile, version, or modded setup.</dd></div><div><dt className="font-semibold text-white">Launch target</dt><dd className="text-slate-400">The executable, URI, desktop entry, Flatpak reference, or script target passed to the native launcher.</dd></div><div><dt className="font-semibold text-white">Source</dt><dd className="text-slate-400">An external game manager or installation system from which Mochi can discover games.</dd></div><div><dt className="font-semibold text-white">Mochi Cloud</dt><dd className="text-slate-400">Optional account-scoped synchronisation of supported metadata.</dd></div><div><dt className="font-semibold text-white">Authenticator app</dt><dd className="text-slate-400">The time-based one-time-code second factor.</dd></div><div><dt className="font-semibold text-white">Cloud access</dt><dd className="text-slate-400">Permission, granted by an administrator, for an Account to use Mochi Cloud.</dd></div><div><dt className="font-semibold text-white">Cloud sync</dt><dd className="text-slate-400">Your own switch for syncing library metadata. Requires Cloud access.</dd></div><div><dt className="font-semibold text-white">Service key</dt><dd className="text-slate-400">A credential for an outside service (IGDB, Nexus Mods) saved privately on your Account.</dd></div></dl></Section>
  <Section id="platforms" title="2. Platform matrix"><div className="overflow-x-auto rounded-2xl border border-white/10"><table className="w-full text-left text-sm"><thead className="bg-white/[0.03] text-slate-400"><tr><th className="p-3">Platform</th><th className="p-3">Status</th><th className="p-3">Notable native features</th></tr></thead><tbody className="divide-y divide-white/10 text-slate-300"><tr><td className="p-3">Linux</td><td className="p-3">Supported (primary, best tested)</td><td className="p-3">AppImage, deb, rpm, Arch PKGBUILD; Flatpak, Lutris, Bottles, Wine/Proton, .desktop, scripts, Steam Deck</td></tr><tr><td className="p-3">macOS 12+</td><td className="p-3">Supported (less tested; not notarized)</td><td className="p-3">Universal DMG; .app, Epic Launcher, Whisky, CrossOver, shell scripts</td></tr><tr><td className="p-3">Windows</td><td className="p-3">Not supported</td><td className="p-3">Windows games can still run through Wine, Proton, or CrossOver</td></tr></tbody></table></div></Section>
  <Section id="targets" title="3. Launch matrix"><p>Linux supports native executables, <code>.desktop</code>, Flatpak IDs, <code>.sh</code>/<code>.bash</code>, <code>.py</code>, <code>.js</code>, <code>.exe</code> via Wine/Proton, and source-specific URIs. macOS supports executables, <code>.app</code>, shell scripts, and <code>.exe</code> via CrossOver or Whisky.</p></Section>
  <Section id="storage" title="4. Storage"><p>The local library and preferences stay on the device. On macOS, config, themes, and artwork live in <code>~/Library/Application Support/Mochi</code>, and playtime and Wine prefixes in <code>~/Library/Application Support/dev.sidequestgames.Mochilauncher</code>. You can move the Mochi data directory from settings.</p></Section>
  <Section id="deeplinks" title="5. Deep links"><p>Mochi handles <code>mochi://launch/&lt;id&gt;</code>, <code>mochi://bigpicture</code>, and the sign-in links <code>mochi://auth/callback</code> and <code>mochi://auth/verify</code>. It also handles <code>nxm://</code> links from Nexus Mods (see Mods &amp; Content). On Linux, Mochi registers only <code>mochi</code> at start.</p></Section>
  <Section id="states" title="6. Feature states"><p><strong>Current</strong> means implemented in the current launcher or website. <strong>Reference</strong> means architectural or explanatory documentation. Roadmap items are directional and are not evidence that a feature is currently implemented.</p></Section>
  <Section id="troubleshooting" title="7. Troubleshooting checklist"><ul className="list-disc space-y-2 pl-6"><li>Confirm the game/source application is installed.</li><li>Confirm a local target or Tofu path still exists.</li><li>For Steam/Heroic/Lutris/Bottles/itch games, verify the source launcher itself can launch the game.</li><li>For Flatpak, verify the application ID with <code>flatpak list</code>.</li><li>For scripts, verify the relevant runtime is installed.</li><li>For mods, verify the Tofu has an install path and the requested version/loader has a compatible file.</li><li>If a network feature fails, check whether Mochi shows the offline banner.</li><li>For account/cloud issues, distinguish authentication problems from cloud-eligibility or synchronisation problems.</li></ul></Section>
</div> }

function Install() { return <div className="space-y-9">
  <Section id="platforms" title="1. Supported platforms"><p>Mochi supports <strong>Linux</strong> (primary, best tested) and <strong>macOS 12.0 or later</strong> on Apple silicon and Intel. <strong>Windows is not supported.</strong> Mochi is in early development, so storage formats and screens may change.</p></Section>
  <Section id="linux" title="2. Linux"><p>Releases ship an AppImage, a <code>.deb</code>, an <code>.rpm</code>, and an Arch PKGBUILD. The AppImage updates itself in place; deb, rpm, and AUR installs only show an “Open release page” prompt, and you update them with your package manager or by downloading the new release. Linux packages are not platform-signed, so use the verification steps below.</p></Section>
  <Section id="macos" title="3. macOS"><p>macOS builds are a universal DMG. They are ad-hoc signed but <strong>not notarized</strong>, so Gatekeeper blocks the first launch. Right-click the app and choose Open, use Open Anyway in System Settings, or run <code>xattr -dr com.apple.quarantine</code> on the app. The macOS app updates itself in place.</p></Section>
  <Section id="verify" title="4. Verified downloads"><p>Only download Mochi from GitHub Releases. Each release includes <code>SHA256SUMS.txt</code>, GPG signatures (<code>.asc</code>) made with the “Mochi Releases” key, and a GitHub build attestation you can check with <code>gh attestation verify</code>. Mochi's public signing key is published in its repository.</p></Section>
  <Section id="updates" title="5. Updates"><p>Mochi checks for updates 10 seconds after start and every 6 hours. It never installs anything until you choose <strong>Install &amp; restart</strong>, and updates are verified against a public key embedded in the app. You can turn automatic checking on or off under Settings → Updates.</p></Section>
  <Section id="offline" title="6. Offline mode"><p>Without a network, your library, launching, playtime, stats, themes, settings, installed-mod management, and cached artwork all keep working. Metadata lookups, Discover, news and deals, sign-in, trailers, and downloads need a network and fail quietly, with an offline banner shown. Bundled theme fonts work offline.</p></Section>
</div> }

function Mods() { return <div className="space-y-9">
  <Section id="overview" title="1. Overview"><p>The <strong>Mods &amp; Content</strong> page discovers mods and installs them into a chosen Tofu. Mochi supports three sources: Modrinth, CurseForge, and Nexus Mods.</p></Section>
  <Section id="sources" title="2. Sources and games"><ul className="list-disc space-y-2 pl-6"><li><strong>Minecraft Java</strong> — Modrinth and CurseForge.</li><li><strong>Other games on CurseForge</strong> — CurseForge first.</li><li><strong>Other games</strong> — Nexus Mods, when you have saved a Nexus Mods service key.</li></ul><p>Switch sources under Settings → Mod sources. When two sites list a game, a switcher lets you pick one, and a short CurseForge list can be extended with Nexus results.</p></Section>
  <Section id="discover" title="3. Discover and install"><p>Browse or search a source, open project details and versions, then install into a Tofu you choose. Downloads run in the background with a host allow-list, a size cap, and SHA-1 verification where available. Third-party descriptions are sanitised.</p></Section>
  <Section id="per-tofu" title="4. Per-Tofu mods"><p>Mods belong to a Tofu, not the whole Piko. Within a Tofu you can enable, disable, or delete mods and keep mod profiles. Mochi identifies existing files (Modrinth by SHA-1, CurseForge by fingerprint, Nexus Mods by MD5) so update checks work for them. Installs and updates extract archives transactionally and reject unsafe paths.</p></Section>
  <Section id="updates" title="5. Update checks"><p>Mochi checks installed mods for updates on all three providers. Updates verify the file hash and keep a rollback copy. Automatic mod updates are off by default; if you turn them on, they run before launch.</p></Section>
  <Section id="nxm" title="6. nxm:// links"><p>Nexus Mods “Mod Manager Download” links open in Mochi and ask which Tofu to install into. Premium Nexus members download through the API; free accounts get a “Download on Nexus” button. Nexus collections are not supported. On Linux, making Mochi the default <code>nxm</code> handler is opt-in from the Mods &amp; Content page.</p></Section>
  <Section id="curseforge" title="7. CurseForge notes"><p>CurseForge uses Mochi's own server-side key, so you need no CurseForge account or key. Results are shown as “Powered by CurseForge”, are not cached, and Mochi links out to the CurseForge page when an author has disabled third-party downloads.</p></Section>
  <Section id="deps" title="8. Dependencies and conflicts"><p>Installing a mod offers its required dependencies (Modrinth, CurseForge, Nexus). An offline conflict check, before launch or on demand, flags duplicates, wrong version or loader, missing dependencies, and incompatible mods.</p></Section>
  <Section id="snapshots" title="9. Snapshots and Update all"><p>Before updating mods Mochi saves a snapshot of the Tofu's mod files and records; Manage Tofus → Snapshots → Restore last working state undoes a bad update. Update all opens a review sheet with changelogs and dependency warnings.</p></Section>
  <Section id="mochipack" title="10. Modpacks (.mochipack)"><p>Manage Tofus → Share exports a Tofu's mod list as a small <code>.mochipack</code> file or a copyable code, holding ids and hashes only, never mod files. Importing shows a preview and installs into a new Tofu or the current one (snapshotted first).</p></Section>
  <Section id="minecraft" title="11. Minecraft instances"><p>There is one Minecraft Piko and each launcher instance is a Tofu, shown as library sub-entries. Instances can be copied on import rather than used in place, and are matched to Modrinth or CurseForge modpacks. Prism, Fjord, PolyMC, and MultiMC instances are imported too.</p></Section>
</div> }

function Experience() { return <div className="space-y-9">
  <Section id="bigpicture" title="1. Big Picture"><p>Big Picture is a fullscreen, controller-first interface. Open it from the top bar, with F11, with Start+Select on a controller, from the tray, with <code>mochi --big-picture</code>, or via <code>mochi://bigpicture</code>. It can also be your startup mode, and it is the default under gamescope. It has display options, power actions, and interface sounds.</p></Section>
  <Section id="controller" title="2. Controller support"><p>Mochi supports Xbox, PlayStation, Switch Pro, Steam Deck, and generic controllers, with an on-screen keyboard for text entry.</p></Section>
  <Section id="steamdeck" title="3. Steam Deck"><p>Mochi detects a Steam Deck and enlarges touch targets to 44px. You can add Mochi to Steam as a non-Steam game so it starts in Big Picture under gamescope.</p></Section>
  <Section id="themes" title="4. Themes"><p>Mochi ships 11 built-in themes: Mochi, Mochi Light, Minecraft Ore, Minecraft Dungeons, Subnautica, Stardew Valley, RuneScape, Fallout Pip-Boy, Cyberpunk 2077, Animal Crossing, and Terraria. Import your own under Settings → Appearance.</p></Section>
  <Section id="accessibility" title="5. Accessibility"><p>Options include text size from 85% to 150%, high contrast, colour-blind palettes, and reduced motion.</p></Section>
  <Section id="sounds" title="6. Interface sounds"><p>Short sounds for navigation, selection, dialogs, launches, downloads, and achievements play in Big Picture (on by default) and optionally in the launcher, with mute, volume, and movement options under Settings → Sound. Built-in packs are Mochi, Chiptune, and Glass, synthesised in code; you can import, export, and remove your own packs, themes can suggest one, and a fallback chain covers a missing pack.</p></Section>
  <Section id="stats" title="7. Playtime and stats"><p>Playtime is credited when a game exits, including games handed to another launcher. The Stats view summarises it, and the tray lists your most-played games.</p></Section>
  <Section id="achievements" title="8. Achievements"><p>Mochi has 77 of its own achievements with rarities, across Playtime, Streaks, Habits, Variety, Library, Explore, Mods, and Steam categories. Per-game Steam achievements are read from local Steam and your public profile; an optional Steam Web API key stays on your device. Cloud saving of Mochi achievements is a per-device toggle in Settings → Achievements (needs sign-in with cloud sync on), and the same section can clear achievements data locally and in the cloud.</p></Section>
</div> }
