import { ArrowLeft, ArrowRight } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'

const sections = [
  { slug: 'getting-started', title: 'Getting Started', description: 'Installation, first launch, games, Pikos, Tofus, and the current workflow.' },
  { slug: 'account', title: 'Account Management', description: 'Accounts, authentication, profiles, security, and cloud access.' },
  { slug: 'pikos-tofus', title: 'Pikos & Tofus', description: 'The core Mochi model for games, environments, profiles, and metadata.' },
  { slug: 'cloud-sync', title: 'Cloud Sync', description: 'Local-first storage, synchronisation, database structure, and access control.' },
]

const headingMap: Record<string, Array<[string,string]>> = {
  'getting-started': [['overview','Overview'],['requirements','Requirements'],['installation','Installation'],['first-launch','First launch'],['add-game','Adding a game'],['tofu','Creating a Tofu'],['launching','Launching games'],['limitations','Current limitations']],
  account: [['model','Account model'],['signin','Sign-in methods'],['sessions','Sessions & persistence'],['profiles','Profiles'],['security','Security'],['cloud-access','Cloud access']],
  'pikos-tofus': [['concepts','Core concepts'],['piko','Piko model'],['tofu','Tofu model'],['relationships','Relationships'],['storage','Local storage'],['future','Future expansion']],
  'cloud-sync': [['principles','Design principles'],['data','Synchronised data'],['pull','Pull behaviour'],['push','Push behaviour'],['database','Database structure'],['security','Access control'],['failure','Failure handling']],
}

export function DocumentationPage() {
  return <div className="space-y-8 pb-10">
    <div><p className="text-sm font-medium uppercase tracking-[0.2em] text-violet-200">Documentation</p><h1 className="mt-3 text-4xl font-black tracking-tight text-white sm:text-5xl">Mochi Documentation</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-300">Formal technical and user documentation for the Mochi launcher. Select a section to understand its architecture, terminology, account system, and cloud behaviour.</p></div>
    <div className="grid gap-5 md:grid-cols-2">{sections.map(s => <Link key={s.slug} to={`/documentation/${s.slug}`} className="glass-card group block p-6 transition hover:-translate-y-0.5 hover:border-violet-400/40 hover:bg-violet-500/[0.05]"><div className="flex justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-violet-300">Documentation</p><h2 className="mt-2 text-xl font-bold text-white">{s.title}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{s.description}</p></div><ArrowRight className="mt-1 h-5 w-5 shrink-0 text-slate-500 group-hover:translate-x-1 group-hover:text-violet-300" /></div></Link>)}</div>
  </div>
}

export function DocumentationArticlePage() {
  const { section: slug } = useParams()
  const index = Math.max(0, sections.findIndex(s => s.slug === slug))
  const current = sections[index]
  const previous = sections[index - 1]
  const next = sections[index + 1]
  const headings = headingMap[current.slug]
  return <div className="grid gap-10 pb-10 lg:grid-cols-[245px_minmax(0,1fr)]">
    <aside className="lg:sticky lg:top-24 lg:h-[calc(100vh-7rem)] lg:overflow-y-auto"><div className="rounded-2xl border border-white/10 bg-slate-900/70 p-4">
      <div className="mb-4 flex items-center justify-between">{previous ? <Link to={`/documentation/${previous.slug}`} className="text-xs text-slate-400 hover:text-white">← Previous</Link> : <Link to="/documentation" className="text-xs text-slate-400 hover:text-white">← Docs</Link>}{next && <Link to={`/documentation/${next.slug}`} className="text-xs text-slate-400 hover:text-white">Next →</Link>}</div>
      <p className="mb-2 text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500">Documentation</p>
      <nav className="space-y-1">{sections.map(s => <Link key={s.slug} to={`/documentation/${s.slug}`} className={`block rounded-lg px-3 py-2 text-sm ${s.slug===current.slug?'bg-violet-500/15 font-semibold text-white':'text-slate-400 hover:bg-white/5 hover:text-white'}`}>{s.title}</Link>)}</nav>
      <div className="my-4 border-t border-white/10" />
      <p className="mb-2 px-3 text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500">On this page</p>
      <nav className="space-y-0.5">{headings.map(([id,label]) => <a key={id} href={`#${id}`} className="block rounded-lg px-3 py-1.5 text-sm text-slate-500 hover:bg-white/5 hover:text-slate-200">{label}</a>)}</nav>
    </div></aside>
    <article id="top" className="min-w-0 max-w-4xl"><header className="mb-10 border-b border-white/10 pb-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-violet-300">Mochi Documentation</p><h1 className="mt-2 text-4xl font-black tracking-tight text-white sm:text-5xl">{current.title}</h1><p className="mt-4 text-lg leading-8 text-slate-300">{current.description}</p></header>
      {current.slug==='getting-started' && <GettingStarted/>}{current.slug==='account' && <Account/>}{current.slug==='pikos-tofus' && <PikosTofus/>}{current.slug==='cloud-sync' && <CloudSync/>}
      <div className="mt-14 grid gap-3 border-t border-white/10 pt-6 sm:grid-cols-2">{previous?<Link to={`/documentation/${previous.slug}`} className="rounded-2xl border border-white/10 p-4 hover:border-white/20"><span className="text-xs text-slate-500">Previous</span><strong className="mt-1 block text-white">← {previous.title}</strong></Link>:<div/>}{next?<Link to={`/documentation/${next.slug}`} className="rounded-2xl border border-white/10 p-4 text-right hover:border-white/20"><span className="text-xs text-slate-500">Next</span><strong className="mt-1 block text-white">{next.title} →</strong></Link>:<div/>}</div>
      <div className="mt-4 text-center"><a href="#top" className="text-xs text-slate-500 hover:text-white">Back to top ↑</a></div>
    </article>
  </div>
}

function Section({id,title,children}:{id:string,title:string,children:React.ReactNode}) { return <section id={id} className="scroll-mt-28 border-b border-white/10 pb-9 pt-2"><h2 className="text-2xl font-bold tracking-tight text-white">{title}</h2><div className="mt-4 space-y-4 text-[15px] leading-7 text-slate-300">{children}</div></section> }

function GettingStarted(){return <div className="space-y-9">
<Section id="overview" title="1. Overview"><p>Mochi is a Linux-first desktop game launcher designed to bring game discovery, local installations, profiles, environments, and launcher tooling into one consistent interface. The design principle is local-first: the launcher should remain useful without requiring game installations to be uploaded to an online service.</p><p>The current release is an early foundation. The React interface establishes the core information architecture, while Tauri and Rust provide the intended native application boundary for operating-system functionality.</p></Section>
<Section id="requirements" title="2. Requirements"><p>Mochi currently uses React 18, TypeScript, Vite, Tauri 2, and Rust. Development requires Node.js/npm and a working Rust/Cargo environment, together with the native dependencies required by Tauri on the target operating system.</p><p>Linux is the primary development target at present. Windows and macOS are longer-term targets rather than claims of complete current support.</p></Section>
<Section id="installation" title="3. Installation"><p>Install frontend dependencies with <code>npm install</code>. Run <code>npm run dev</code> for the frontend development server, or <code>npm run tauri dev</code> to run the desktop application. A frontend production build uses <code>npm run build</code>; packaged desktop builds use <code>npm run tauri build</code>.</p><p>The Tauri configuration points development builds at the Vite server and packages the generated <code>dist</code> directory into the native application.</p></Section>
<Section id="first-launch" title="4. First launch"><p>Mochi starts with a local library model. The interface allows users to view Pikos, select Tofus, change launcher preferences, and work with account functionality when configured.</p><p>Current local persistence uses browser storage from the React frontend. The native layer is intentionally minimal today and is the planned location for filesystem, process, detection, and other operating-system responsibilities.</p></Section>
<Section id="add-game" title="5. Adding a game"><p>A game is represented as a Piko. The current custom-game workflow records a name and executable path, creates a local Piko, and gives it a default Tofu. Installed-game detection is represented in the interface but remains a planned native feature.</p><p>Optional IGDB lookup can retrieve game metadata and artwork. Its credentials are configured as launcher settings and are used directly for metadata requests rather than being stored in the cloud library.</p></Section>
<Section id="tofu" title="6. Creating a Tofu"><p>A Tofu is an independent environment belonging to a Piko. It currently records a name, game version, runtime, mod count, and readiness status. Typical environments might be Vanilla, Fabric, Performance, or Development.</p><p>The separation is intentional: the Piko identifies the game, while the Tofu describes how that game is configured or intended to run.</p></Section>
<Section id="launching" title="7. Launching games"><p>The interface exposes a Play action for the selected Piko. The present implementation demonstrates launcher state transitions, while comprehensive executable discovery and native process management are still under development. The Rust/Tauri layer is intended to own reliable process lifecycle operations in the mature launcher.</p></Section>
<Section id="limitations" title="8. Current limitations"><p>Mochi is early development software. Automatic game detection, comprehensive runtime management, mod management, platform integrations, and complete native process control are planned capabilities. Documentation distinguishes these roadmap items from functionality currently implemented in the frontend.</p></Section>
</div>}

function Account(){return <div className="space-y-9">
<Section id="model" title="1. Account model"><p>Mochi accounts provide a shared identity for the website and launcher. Account functionality is optional for the local-first launcher experience. Authentication establishes identity; cloud synchronisation is a separate capability.</p></Section>
<Section id="signin" title="2. Sign-in methods"><p>The current account interface supports Google, GitHub, email and password, and passwordless magic links delivered to an email address. Phone-number sign-in is not supported.</p><p>The website handles the user-facing flow and session state. External identity providers authenticate users through their own systems, while email-based methods use the account service configured for Mochi.</p></Section>
<Section id="sessions" title="3. Sessions & persistence"><p>The launcher persists authenticated sessions, refreshes tokens automatically, and detects authentication results returned through the browser. This allows users to return without repeatedly completing the full sign-in process.</p><p>Signing out terminates the current authenticated session. Local launcher data is a separate storage concern and is not automatically deleted by signing out.</p></Section>
<Section id="profiles" title="4. Profiles"><p>The cloud schema contains a profile associated one-to-one with an account. It supports a display name, avatar URL, cloud-sync preference, metadata access state, and timestamps. A database trigger creates a profile when a new account is created.</p></Section>
<Section id="security" title="5. Security"><p>Mochi supports time-based one-time-password authentication through an authenticator application. A verified factor can be challenged when additional verification is required.</p><p>Users should also protect their email account and any external identity provider account used with Mochi. Account security is a shared responsibility between the service and the user's device and credentials.</p></Section>
<Section id="cloud-access" title="6. Cloud access"><p>Cloud access is distinct from account creation. The current product includes administrative controls intended to allow or disable metadata synchronisation for individual users. A user can therefore have an account without necessarily having cloud metadata access.</p></Section>
</div>}

function PikosTofus(){return <div className="space-y-9">
<Section id="concepts" title="1. Core concepts"><p>Mochi uses two primary domain concepts. A <strong>Piko</strong> is a game managed by Mochi. A <strong>Tofu</strong> is an individual environment, profile, runtime configuration, or mod setup belonging to that game.</p><p>This hierarchy keeps the identity of a game stable while allowing multiple independent environments to coexist.</p></Section>
<Section id="piko" title="2. Piko model"><p>The current Piko model contains an identifier, name, description, accent, artwork, optional artwork URL, optional executable path, source classification, and a collection of Tofus. Sources distinguish built-in and custom entries.</p><p>Executable paths are machine-specific integration data. They should not be assumed to be valid when a library is moved to another computer.</p></Section>
<Section id="tofu" title="3. Tofu model"><p>A Tofu contains an identifier, name, version, runtime, installed-mod count, and status. Status currently distinguishes <em>Ready</em> from <em>Needs attention</em>.</p><p>Names are intentionally flexible. Mochi does not require every user to structure environments in the same way.</p></Section>
<Section id="relationships" title="4. Relationships"><p>Each Tofu belongs to exactly one Piko. In cloud storage, Tofus reference their parent Piko while local identifiers provide stable keys for synchronisation.</p><p>Deleting a Piko in the cloud database cascades to its Tofus, preventing orphaned records.</p></Section>
<Section id="storage" title="5. Local storage"><p>The current frontend stores the library and launcher settings locally. This includes Piko data and preferences such as theme, behaviour settings, and optional IGDB configuration.</p><p>The future native storage architecture can build on the same model while moving filesystem-sensitive responsibilities into the Tauri/Rust layer.</p></Section>
<Section id="future" title="6. Future expansion"><p>The model is intentionally extensible. Planned capabilities include runtime management, mod loaders, platform integrations, installation detection, process state, and richer launch configuration.</p><p>Future additions should preserve the Piko-to-Tofu ownership model and stable local identifiers so local operation remains independent from cloud availability.</p></Section>
</div>}

function CloudSync(){return <div className="space-y-9">
<Section id="principles" title="1. Design principles"><p>Mochi Cloud is an optional metadata service around a local-first launcher. It is intended to synchronise supported account information, launcher metadata, configurations, and settings rather than host complete game installations.</p><p>This separation reduces dependence on network availability and avoids turning large local game files into cloud-managed assets.</p></Section>
<Section id="data" title="2. Synchronised data"><p>The current schema stores profiles, Pikos, and Tofus. Piko records include names, descriptions, accents, artwork, source classification, and executable-path metadata. Tofu records include names, versions, runtimes, mod counts, and status.</p><p>Optional IGDB credentials are local launcher settings and are not part of the cloud Piko/Tofu schema.</p></Section>
<Section id="pull" title="3. Pull behaviour"><p>When an authenticated launcher begins synchronisation, it retrieves Pikos owned by the current account and then retrieves their Tofus. If cloud data exists, it is loaded into the local library state.</p><p>If the account has no cloud library yet, the local library can initialise the cloud representation.</p></Section>
<Section id="push" title="4. Push behaviour"><p>Library records are upserted using the authenticated user and stable local identifiers. Tofus are upserted beneath their corresponding Piko. Records that no longer exist locally are removed from the cloud representation so synchronised state does not accumulate stale entries.</p><p>The current implementation is a straightforward replication model, not a full multi-device conflict-resolution system.</p></Section>
<Section id="database" title="5. Database structure"><p>The current schema defines <code>profiles</code>, <code>pikos</code>, and <code>tofus</code>. Profiles belong to an account. Pikos belong to an account. Tofus belong to a Piko.</p><p>Unique constraints prevent duplicate local identifiers within their ownership scope, and indexes support common ownership and parent-child queries.</p></Section>
<Section id="security" title="6. Access control"><p>Row-level security is enabled on the application tables. Profile policies restrict records to the owning account. Piko policies restrict access to records owned by the authenticated user. Tofu policies verify ownership through the parent Piko.</p><p>This database-level authorisation is important because client-side identifiers alone must never be treated as proof of ownership.</p></Section>
<Section id="failure" title="7. Failure handling"><p>Synchronisation failures are represented as an error state rather than being silently treated as successful. The local library remains available because cloud services are not intended to be a prerequisite for basic local operation.</p><p>Before sophisticated concurrent multi-device editing is introduced, explicit conflict-resolution rules should be defined so users can understand which changes win and why.</p></Section>
</div>}
